[theme]
base = "light"
primaryColor = "#6B4EFF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7FB"
textColor = "#111111"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "auto"
